package main.java.org.quantumatic.amethyst.ast;

public enum TokenKind {
    AMPERSAND("`&`"),
    AMPERSAND_EQ("`&=`"),
    DOUBLE_AMPERSAND("`&&`"),
    ASTERISK("`*`"),
    DOUBLE_ASTERISK("`**`"),
    ASTERISK_EQ("`*=`"),
    AT("`@`"),
    BANG("`!`"),
    CLOSE_BRACE("`}`"),
    CLOSE_BRACKET("`]`"),
    CLOSE_PARENT("`)`"),
    COLON("`:`"),
    COMMA("`,`"),
    DOT("`.`"),
    DOUBLE_DOT("`..`"),
    EQ("`=`"),
    DOUBLE_EQ("`==`"),
    GREATER("`>`"),
    GREATER_EQ("`>=`"),
    LEFT_SHIFT("`<<`"),
    LESS("`<`"),
    MINUS("`-`"),
    MINUS_EQ("`-=`"),
    DOUBLE_MINUS("`--`"),
    TILDE("`~`"),
    BANG_EQ("`!=`"),
    OPEN_BRACE("`[`"),
    OPEN_PARENT("`(`"),
    OR("`|`"),
    OR_EQ("`|=`"),
    DOUBLE_OR("`||`"),
    PERCENT("`%`"),
    PERCENT_EQ("`%=`"),
    PLUS("`+`"),
    PLUS_EQ("`+=`"),
    DOUBLE_PLUS("`++`"),
    QUESTION_MARK("`?`"),
    RIGHT_SHIFT("`>>`"),
    SEMICOLON("`;`"),
    SLASH("`/`"),
    SLASH_EQ("`/=`"),
    CARET("`^`"),
    CARET_EQ("`^=`"),
    HASHTAG("`#`"),
    UNDERSCORE("`_`"),
    IDENTIFIER("identifier");

    TokenKind(String value) {}
}
